services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    restart: always
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./web:/app/web
    depends_on:
      - api
    restart: always
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    volumes:
      - api_data:/app/api
    depends_on:
      - db
    restart: always
volumes:
  postgresql_data:
  api_data:
